import { Navbar } from "@/components";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { classname } from "@/helpers/classname";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={classname("bg-fuchsia-950" , geistSans.className , geistMono.className) }>
        
        <Navbar />

        {children}
      </body>
    </html>
  );
}
